# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bimagrid.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'bimagrid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62imagrid.proto\x12\x08\x62imagrid\"\xae\x01\n\x11OracleDataRequest\x12\x11\n\toracle_id\x18\x01 \x01(\t\x12\x10\n\x08h3_index\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x13\n\x0brainfall_mm\x18\x04 \x01(\x01\x12\x0c\n\x04ndvi\x18\x05 \x01(\x01\x12\x15\n\rsoil_moisture\x18\x06 \x01(\x01\x12\x14\n\x0c\x64\x61ta_sources\x18\x07 \x03(\t\x12\x11\n\tsignature\x18\x08 \x01(\t\"6\n\x12OracleDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"n\n\x15RegisterFarmerRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x11\n\tward_code\x18\x02 \x01(\t\x12\x0c\n\x04\x63rop\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x63reage\x18\x04 \x01(\t\x12\x14\n\x0cmpesa_number\x18\x05 \x01(\t\"Q\n\x16RegisterFarmerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rpolicy_number\x18\x03 \x01(\t\"$\n\x13PolicyStatusRequest\x12\r\n\x05phone\x18\x01 \x01(\t\"c\n\x14PolicyStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x19\n\x11next_payment_date\x18\x04 \x01(\t\"I\n\x10\x46ileClaimRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x11\n\tloss_type\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"N\n\x11\x46ileClaimResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x0f\x63laim_reference\x18\x03 \x01(\t2X\n\rOracleService\x12G\n\nSubmitData\x12\x1b.bimagrid.OracleDataRequest\x1a\x1c.bimagrid.OracleDataResponse2\xfa\x01\n\x0bUssdService\x12S\n\x0eRegisterFarmer\x12\x1f.bimagrid.RegisterFarmerRequest\x1a .bimagrid.RegisterFarmerResponse\x12P\n\x0fGetPolicyStatus\x12\x1d.bimagrid.PolicyStatusRequest\x1a\x1e.bimagrid.PolicyStatusResponse\x12\x44\n\tFileClaim\x12\x1a.bimagrid.FileClaimRequest\x1a\x1b.bimagrid.FileClaimResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bimagrid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORACLEDATAREQUEST']._serialized_start=29
  _globals['_ORACLEDATAREQUEST']._serialized_end=203
  _globals['_ORACLEDATARESPONSE']._serialized_start=205
  _globals['_ORACLEDATARESPONSE']._serialized_end=259
  _globals['_REGISTERFARMERREQUEST']._serialized_start=261
  _globals['_REGISTERFARMERREQUEST']._serialized_end=371
  _globals['_REGISTERFARMERRESPONSE']._serialized_start=373
  _globals['_REGISTERFARMERRESPONSE']._serialized_end=454
  _globals['_POLICYSTATUSREQUEST']._serialized_start=456
  _globals['_POLICYSTATUSREQUEST']._serialized_end=492
  _globals['_POLICYSTATUSRESPONSE']._serialized_start=494
  _globals['_POLICYSTATUSRESPONSE']._serialized_end=593
  _globals['_FILECLAIMREQUEST']._serialized_start=595
  _globals['_FILECLAIMREQUEST']._serialized_end=668
  _globals['_FILECLAIMRESPONSE']._serialized_start=670
  _globals['_FILECLAIMRESPONSE']._serialized_end=748
  _globals['_ORACLESERVICE']._serialized_start=750
  _globals['_ORACLESERVICE']._serialized_end=838
  _globals['_USSDSERVICE']._serialized_start=841
  _globals['_USSDSERVICE']._serialized_end=1091
# @@protoc_insertion_point(module_scope)
