/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVerification,
  IVerificationInterface,
} from "../../../contracts/interfaces/IVerification";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "policyId",
        type: "uint256",
      },
    ],
    name: "calculateDiscount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "policyId",
        type: "uint256",
      },
    ],
    name: "getPolicyMitigations",
    outputs: [
      {
        internalType: "string[]",
        name: "",
        type: "string[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "mitigationType",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "discountPercent",
        type: "uint256",
      },
    ],
    name: "setMitigationDiscount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "policyId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "mitigationType",
        type: "string",
      },
    ],
    name: "verifyMitigation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVerification__factory {
  static readonly abi = _abi;
  static createInterface(): IVerificationInterface {
    return new Interface(_abi) as IVerificationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVerification {
    return new Contract(address, _abi, runner) as unknown as IVerification;
  }
}
