# Generated by Django 4.2.30 on 2026-07-01 11:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "onboarding",
            "0002_rename_onboarding_l_h3_ind_5b8d56_idx_onboarding__h3_inde_ca6593_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ParcelGeometry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("h3_index", models.CharField(db_index=True, max_length=32)),
                ("ward_code", models.CharField(blank=True, max_length=32)),
                ("geometry_geojson", models.JSONField(default=dict)),
                ("centroid", models.JSONField(blank=True, default=dict)),
                (
                    "acreage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("source", models.CharField(default="manual", max_length=64)),
                (
                    "onboarding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcel_geometries",
                        to="onboarding.farmeronboarding",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
