# Generated by Django 4.2.30 on 2026-07-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geospatial", "0002_h3grid_gridrisk"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gridrisk",
            new_name="geospatial__h3_inde_74e010_idx",
            old_name="geospatial__h3_inde_4c9f1d_idx",
        ),
        migrations.RenameIndex(
            model_name="h3grid",
            new_name="geospatial__resolut_d35805_idx",
            old_name="geospatial__resolut_6a8b2a_idx",
        ),
    ]
