# Generated by Django 4.2.30 on 2026-07-02 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0003_rename_geospatial__h3_inde_4c9f1d_idx_geospatial__h3_inde_74e010_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'constituencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcounties', to='geospatial.county')),
            ],
            options={
                'verbose_name_plural': 'subcounties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='geospatial.constituency')),
                ('subcounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='geospatial.subcounty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='constituency',
            name='subcounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='geospatial.subcounty'),
        ),
        migrations.CreateModel(
            name='WardProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('mean_rainfall_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ndvi_baseline', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('drought_risk_score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('flood_risk_score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('data_sources', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('profiled_at', models.DateTimeField(blank=True, null=True)),
                ('ward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='geospatial.ward')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='geospatial__status_3a9419_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['constituency', 'name'], name='geospatial__constit_912526_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['subcounty', 'name'], name='geospatial__subcoun_711106_idx'),
        ),
        migrations.AddIndex(
            model_name='subcounty',
            index=models.Index(fields=['county', 'name'], name='geospatial__county__e32cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='constituency',
            index=models.Index(fields=['subcounty', 'name'], name='geospatial__subcoun_702cd0_idx'),
        ),
    ]
