# Generated by Django 4.2.30 on 2026-07-01 11:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "accounts",
            "0002_rename_accounts_pr_phone_n_3f4f97_idx_accounts_pr_phone_n_c27a97_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("crop", models.CharField(max_length=32, unique=True)),
                (
                    "base_rate_per_acre",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "drought_multiplier",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
                (
                    "flood_multiplier",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
                (
                    "mitigation_discount_cap",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["crop"],
            },
        ),
        migrations.CreateModel(
            name="PremiumQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("crop", models.CharField(max_length=32)),
                ("acreage", models.DecimalField(decimal_places=2, max_digits=8)),
                ("base_premium", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("final_premium", models.DecimalField(decimal_places=2, max_digits=12)),
                ("risk_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_quotes",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
