# Generated by Django 4.2.30 on 2026-07-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='insured_value_per_acre',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=12),
        ),
    ]
