# Generated by Django 4.2.30 on 2026-07-01 11:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SatelliteObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("h3_index", models.CharField(db_index=True, max_length=32)),
                ("scene_id", models.CharField(max_length=128)),
                ("source", models.CharField(default="sentinel-2", max_length=64)),
                ("metric_name", models.CharField(max_length=64)),
                ("metric_value", models.DecimalField(decimal_places=4, max_digits=12)),
                ("observed_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SatelliteAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("analysis_type", models.CharField(max_length=64)),
                ("result", models.JSONField(default=dict)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="satellite.satelliteobservation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
