# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import bimagrid_pb2 as bimagrid__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bimagrid_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OracleServiceStub:
    """==========================================
    Oracle Integration (Rust -> Python)
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitData = channel.unary_unary(
                '/bimagrid.OracleService/SubmitData',
                request_serializer=bimagrid__pb2.OracleDataRequest.SerializeToString,
                response_deserializer=bimagrid__pb2.OracleDataResponse.FromString,
                _registered_method=True)


class OracleServiceServicer:
    """==========================================
    Oracle Integration (Rust -> Python)
    ==========================================
    """

    def SubmitData(self, request, context):
        """Submit off-chain cryptographically signed data to the backend
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OracleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitData': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitData,
                    request_deserializer=bimagrid__pb2.OracleDataRequest.FromString,
                    response_serializer=bimagrid__pb2.OracleDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bimagrid.OracleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bimagrid.OracleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OracleService:
    """==========================================
    Oracle Integration (Rust -> Python)
    ==========================================
    """

    @staticmethod
    def SubmitData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bimagrid.OracleService/SubmitData',
            bimagrid__pb2.OracleDataRequest.SerializeToString,
            bimagrid__pb2.OracleDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UssdServiceStub:
    """==========================================
    USSD Integration (Python USSD -> Python Backend)
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterFarmer = channel.unary_unary(
                '/bimagrid.UssdService/RegisterFarmer',
                request_serializer=bimagrid__pb2.RegisterFarmerRequest.SerializeToString,
                response_deserializer=bimagrid__pb2.RegisterFarmerResponse.FromString,
                _registered_method=True)
        self.GetPolicyStatus = channel.unary_unary(
                '/bimagrid.UssdService/GetPolicyStatus',
                request_serializer=bimagrid__pb2.PolicyStatusRequest.SerializeToString,
                response_deserializer=bimagrid__pb2.PolicyStatusResponse.FromString,
                _registered_method=True)
        self.FileClaim = channel.unary_unary(
                '/bimagrid.UssdService/FileClaim',
                request_serializer=bimagrid__pb2.FileClaimRequest.SerializeToString,
                response_deserializer=bimagrid__pb2.FileClaimResponse.FromString,
                _registered_method=True)


class UssdServiceServicer:
    """==========================================
    USSD Integration (Python USSD -> Python Backend)
    ==========================================
    """

    def RegisterFarmer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicyStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileClaim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UssdServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterFarmer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterFarmer,
                    request_deserializer=bimagrid__pb2.RegisterFarmerRequest.FromString,
                    response_serializer=bimagrid__pb2.RegisterFarmerResponse.SerializeToString,
            ),
            'GetPolicyStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicyStatus,
                    request_deserializer=bimagrid__pb2.PolicyStatusRequest.FromString,
                    response_serializer=bimagrid__pb2.PolicyStatusResponse.SerializeToString,
            ),
            'FileClaim': grpc.unary_unary_rpc_method_handler(
                    servicer.FileClaim,
                    request_deserializer=bimagrid__pb2.FileClaimRequest.FromString,
                    response_serializer=bimagrid__pb2.FileClaimResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bimagrid.UssdService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bimagrid.UssdService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UssdService:
    """==========================================
    USSD Integration (Python USSD -> Python Backend)
    ==========================================
    """

    @staticmethod
    def RegisterFarmer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bimagrid.UssdService/RegisterFarmer',
            bimagrid__pb2.RegisterFarmerRequest.SerializeToString,
            bimagrid__pb2.RegisterFarmerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicyStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bimagrid.UssdService/GetPolicyStatus',
            bimagrid__pb2.PolicyStatusRequest.SerializeToString,
            bimagrid__pb2.PolicyStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileClaim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bimagrid.UssdService/FileClaim',
            bimagrid__pb2.FileClaimRequest.SerializeToString,
            bimagrid__pb2.FileClaimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
