/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockOracle } from "./MockOracle";
export type { MockToken } from "./MockToken";
export type { MockWeatherFeed } from "./MockWeatherFeed";
