/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockWeatherFeedInterface extends Interface {
  getFunction(nameOrSignature: "reports" | "updateReport"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ReportUpdated"): EventFragment;

  encodeFunctionData(functionFragment: "reports", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "updateReport",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "reports", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateReport",
    data: BytesLike
  ): Result;
}

export namespace ReportUpdatedEvent {
  export type InputTuple = [
    h3Index: BytesLike,
    rainfall: BigNumberish,
    ndvi: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    h3Index: string,
    rainfall: bigint,
    ndvi: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    h3Index: string;
    rainfall: bigint;
    ndvi: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockWeatherFeed extends BaseContract {
  connect(runner?: ContractRunner | null): MockWeatherFeed;
  waitForDeployment(): Promise<this>;

  interface: MockWeatherFeedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  reports: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint] & {
        rainfall: bigint;
        ndvi: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  updateReport: TypedContractMethod<
    [h3Index: BytesLike, rainfall: BigNumberish, ndvi: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "reports"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint] & {
        rainfall: bigint;
        ndvi: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateReport"
  ): TypedContractMethod<
    [h3Index: BytesLike, rainfall: BigNumberish, ndvi: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ReportUpdated"
  ): TypedContractEvent<
    ReportUpdatedEvent.InputTuple,
    ReportUpdatedEvent.OutputTuple,
    ReportUpdatedEvent.OutputObject
  >;

  filters: {
    "ReportUpdated(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      ReportUpdatedEvent.InputTuple,
      ReportUpdatedEvent.OutputTuple,
      ReportUpdatedEvent.OutputObject
    >;
    ReportUpdated: TypedContractEvent<
      ReportUpdatedEvent.InputTuple,
      ReportUpdatedEvent.OutputTuple,
      ReportUpdatedEvent.OutputObject
    >;
  };
}
