/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BimaToken__factory } from "./BimaToken__factory";
export { PolicyNFT__factory } from "./PolicyNFT__factory";
