# Generated by Django 4.2.30 on 2026-07-01 11:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "onboarding",
            "0002_rename_onboarding_l_h3_ind_5b8d56_idx_onboarding__h3_inde_ca6593_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("policy_number", models.CharField(max_length=40, unique=True)),
                (
                    "crop",
                    models.CharField(
                        choices=[
                            ("maize", "Maize"),
                            ("beans", "Beans"),
                            ("sorghum", "Sorghum"),
                            ("wheat", "Wheat"),
                            ("rice", "Rice"),
                            ("coffee", "Coffee"),
                            ("tea", "Tea"),
                            ("potato", "Potato"),
                            ("mixed", "Mixed Crops"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "insured_acreage",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("coverage_h3", models.CharField(db_index=True, max_length=32)),
                (
                    "premium_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("coverage_start", models.DateField()),
                ("coverage_end", models.DateField()),
                (
                    "mitigation_discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("lapsed", "Lapsed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "onboarding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="onboarding.farmeronboarding",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=64)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["policy_number"], name="policies_po_policy__a03f9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["coverage_h3"], name="policies_po_coverag_8444aa_idx"
            ),
        ),
    ]
