# Generated by Django 4.2.30 on 2026-07-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("lapsed", "Lapsed"),
                    ("cancelled", "Cancelled"),
                    ("paid_out", "Paid Out"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
