# Generated by Django 4.2.30 on 2026-07-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="profile",
            new_name="accounts_pr_phone_n_c27a97_idx",
            old_name="accounts_pr_phone_n_3f4f97_idx",
        ),
        migrations.RenameIndex(
            model_name="profile",
            new_name="accounts_pr_nationa_cfd8da_idx",
            old_name="accounts_pr_national_7f72d5_idx",
        ),
    ]
