# Generated by Django 4.2.30 on 2026-07-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_accounts_pr_phone_n_3f4f97_idx_accounts_pr_phone_n_c27a97_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requires_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
