# Generated by Django 4.2.30 on 2026-07-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_requires_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('farmer', 'Farmer'), ('broker', 'Broker'), ('coop', 'Co-op'), ('admin', 'Admin')], default='customer', max_length=16),
        ),
    ]
