/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockWeatherFeed,
  MockWeatherFeedInterface,
} from "../../../contracts/mocks/MockWeatherFeed";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "h3Index",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rainfall",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "ndvi",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "ReportUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "reports",
    outputs: [
      {
        internalType: "uint256",
        name: "rainfall",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "ndvi",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "h3Index",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "rainfall",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "ndvi",
        type: "uint256",
      },
    ],
    name: "updateReport",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461001657610179908161001c8239f35b600080fdfe60806040818152600436101561001457600080fd5b600091823560e01c9081637e8036651461007b575063b39c48971461003857600080fd5b34610077576020366003190112610077576004358252602082815291819020805460018201546002909201549251908152928301526040820152606090f35b5080fd5b9190503461013f57606036600319011261013f576004359160243591604435916060810181811067ffffffffffffffff82111761012b5791610125917f31b69995c209bd81da3557942590dfc28441227b5e83086f5117bd61c515dc88959493825284815260026020820185815283830190428252898b528a602052848b209351845551600184015551910155519283924291846040919493926060820195825260208201520152565b0390a280f35b634e487b7160e01b87526041600452602487fd5b8280fdfea26469706673582212202bf46919156d852de0456ddbed77abace8f34b7ec884d722ed1fd9a115469cc064736f6c63430008140033";

type MockWeatherFeedConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockWeatherFeedConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockWeatherFeed__factory extends ContractFactory {
  constructor(...args: MockWeatherFeedConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockWeatherFeed & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockWeatherFeed__factory {
    return super.connect(runner) as MockWeatherFeed__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockWeatherFeedInterface {
    return new Interface(_abi) as MockWeatherFeedInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockWeatherFeed {
    return new Contract(address, _abi, runner) as unknown as MockWeatherFeed;
  }
}
