# Generated by Django 4.2.30 on 2026-07-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="landparcel",
            new_name="onboarding__h3_inde_ca6593_idx",
            old_name="onboarding_l_h3_ind_5b8d56_idx",
        ),
    ]
