# Generated by Django 4.2.30 on 2026-07-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0003_farmeronboarding_assigned_agent"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="farmeronboarding",
            name="onboarding__assigned_7a1b2c_idx",
        ),
    ]
