# Generated by Django 4.2.30 on 2026-07-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0004_kenya_admin_geography'),
        ('onboarding', '0004_remove_farmeronboarding_onboarding__assigned_7a1b2c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmeronboarding',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings', to='geospatial.ward'),
        ),
    ]
