/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface BimaGridPolicyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createPolicy"
      | "nextPolicyId"
      | "oracleNode"
      | "owner"
      | "policies"
      | "setOracleNode"
      | "triggerPayout"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PayoutTriggered" | "PolicyCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createPolicy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPolicyId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oracleNode",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracleNode",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerPayout",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextPolicyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracleNode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setOracleNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerPayout",
    data: BytesLike
  ): Result;
}

export namespace PayoutTriggeredEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    farmer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [policyId: bigint, farmer: string, amount: bigint];
  export interface OutputObject {
    policyId: bigint;
    farmer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyCreatedEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    farmer: AddressLike,
    payoutAmount: BigNumberish
  ];
  export type OutputTuple = [
    policyId: bigint,
    farmer: string,
    payoutAmount: bigint
  ];
  export interface OutputObject {
    policyId: bigint;
    farmer: string;
    payoutAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BimaGridPolicy extends BaseContract {
  connect(runner?: ContractRunner | null): BimaGridPolicy;
  waitForDeployment(): Promise<this>;

  interface: BimaGridPolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createPolicy: TypedContractMethod<
    [_farmer: AddressLike, _payoutAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  nextPolicyId: TypedContractMethod<[], [bigint], "view">;

  oracleNode: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  policies: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean] & {
        farmer: string;
        payoutAmount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  setOracleNode: TypedContractMethod<
    [_oracleNode: AddressLike],
    [void],
    "nonpayable"
  >;

  triggerPayout: TypedContractMethod<
    [_policyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createPolicy"
  ): TypedContractMethod<
    [_farmer: AddressLike, _payoutAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextPolicyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracleNode"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policies"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean] & {
        farmer: string;
        payoutAmount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setOracleNode"
  ): TypedContractMethod<[_oracleNode: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "triggerPayout"
  ): TypedContractMethod<[_policyId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "PayoutTriggered"
  ): TypedContractEvent<
    PayoutTriggeredEvent.InputTuple,
    PayoutTriggeredEvent.OutputTuple,
    PayoutTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "PolicyCreated"
  ): TypedContractEvent<
    PolicyCreatedEvent.InputTuple,
    PolicyCreatedEvent.OutputTuple,
    PolicyCreatedEvent.OutputObject
  >;

  filters: {
    "PayoutTriggered(uint256,address,uint256)": TypedContractEvent<
      PayoutTriggeredEvent.InputTuple,
      PayoutTriggeredEvent.OutputTuple,
      PayoutTriggeredEvent.OutputObject
    >;
    PayoutTriggered: TypedContractEvent<
      PayoutTriggeredEvent.InputTuple,
      PayoutTriggeredEvent.OutputTuple,
      PayoutTriggeredEvent.OutputObject
    >;

    "PolicyCreated(uint256,address,uint256)": TypedContractEvent<
      PolicyCreatedEvent.InputTuple,
      PolicyCreatedEvent.OutputTuple,
      PolicyCreatedEvent.OutputObject
    >;
    PolicyCreated: TypedContractEvent<
      PolicyCreatedEvent.InputTuple,
      PolicyCreatedEvent.OutputTuple,
      PolicyCreatedEvent.OutputObject
    >;
  };
}
