/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EscrowVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedCallers"
      | "claimRefund"
      | "depositPremium"
      | "owner"
      | "payout"
      | "pendingRefunds"
      | "premiums"
      | "refundPremium"
      | "renounceOwnership"
      | "setAuthorizedCaller"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CallerAuthorized"
      | "OwnershipTransferred"
      | "PayoutExecuted"
      | "PremiumDeposited"
      | "RefundClaimed"
      | "RefundPending"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedCallers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositPremium",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payout",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRefunds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "premiums",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refundPremium",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedCaller",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositPremium",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payout", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingRefunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "premiums", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundPremium",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CallerAuthorizedEvent {
  export type InputTuple = [caller: AddressLike, authorized: boolean];
  export type OutputTuple = [caller: string, authorized: boolean];
  export interface OutputObject {
    caller: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutExecutedEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    farmer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [policyId: bigint, farmer: string, amount: bigint];
  export interface OutputObject {
    policyId: bigint;
    farmer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PremiumDepositedEvent {
  export type InputTuple = [policyId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [policyId: bigint, amount: bigint];
  export interface OutputObject {
    policyId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [farmer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [farmer: string, amount: bigint];
  export interface OutputObject {
    farmer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundPendingEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    farmer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [policyId: bigint, farmer: string, amount: bigint];
  export interface OutputObject {
    policyId: bigint;
    farmer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowVault extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowVault;
  waitForDeployment(): Promise<this>;

  interface: EscrowVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedCallers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  claimRefund: TypedContractMethod<[], [void], "nonpayable">;

  depositPremium: TypedContractMethod<
    [policyId: BigNumberish],
    [void],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payout: TypedContractMethod<
    [policyId: BigNumberish, farmer: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  pendingRefunds: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  premiums: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  refundPremium: TypedContractMethod<
    [policyId: BigNumberish, farmer: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuthorizedCaller: TypedContractMethod<
    [caller: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedCallers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositPremium"
  ): TypedContractMethod<[policyId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payout"
  ): TypedContractMethod<
    [policyId: BigNumberish, farmer: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pendingRefunds"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "premiums"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "refundPremium"
  ): TypedContractMethod<
    [policyId: BigNumberish, farmer: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedCaller"
  ): TypedContractMethod<
    [caller: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CallerAuthorized"
  ): TypedContractEvent<
    CallerAuthorizedEvent.InputTuple,
    CallerAuthorizedEvent.OutputTuple,
    CallerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayoutExecuted"
  ): TypedContractEvent<
    PayoutExecutedEvent.InputTuple,
    PayoutExecutedEvent.OutputTuple,
    PayoutExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PremiumDeposited"
  ): TypedContractEvent<
    PremiumDepositedEvent.InputTuple,
    PremiumDepositedEvent.OutputTuple,
    PremiumDepositedEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RefundPending"
  ): TypedContractEvent<
    RefundPendingEvent.InputTuple,
    RefundPendingEvent.OutputTuple,
    RefundPendingEvent.OutputObject
  >;

  filters: {
    "CallerAuthorized(address,bool)": TypedContractEvent<
      CallerAuthorizedEvent.InputTuple,
      CallerAuthorizedEvent.OutputTuple,
      CallerAuthorizedEvent.OutputObject
    >;
    CallerAuthorized: TypedContractEvent<
      CallerAuthorizedEvent.InputTuple,
      CallerAuthorizedEvent.OutputTuple,
      CallerAuthorizedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayoutExecuted(uint256,address,uint256)": TypedContractEvent<
      PayoutExecutedEvent.InputTuple,
      PayoutExecutedEvent.OutputTuple,
      PayoutExecutedEvent.OutputObject
    >;
    PayoutExecuted: TypedContractEvent<
      PayoutExecutedEvent.InputTuple,
      PayoutExecutedEvent.OutputTuple,
      PayoutExecutedEvent.OutputObject
    >;

    "PremiumDeposited(uint256,uint128)": TypedContractEvent<
      PremiumDepositedEvent.InputTuple,
      PremiumDepositedEvent.OutputTuple,
      PremiumDepositedEvent.OutputObject
    >;
    PremiumDeposited: TypedContractEvent<
      PremiumDepositedEvent.InputTuple,
      PremiumDepositedEvent.OutputTuple,
      PremiumDepositedEvent.OutputObject
    >;

    "RefundClaimed(address,uint256)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;

    "RefundPending(uint256,address,uint256)": TypedContractEvent<
      RefundPendingEvent.InputTuple,
      RefundPendingEvent.OutputTuple,
      RefundPendingEvent.OutputObject
    >;
    RefundPending: TypedContractEvent<
      RefundPendingEvent.InputTuple,
      RefundPendingEvent.OutputTuple,
      RefundPendingEvent.OutputObject
    >;
  };
}
