/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface KilimaShieldOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "escrowVault"
      | "getMedian"
      | "isAuthorizedOracle"
      | "oracleCount"
      | "owner"
      | "policyRegistry"
      | "registerPolicy"
      | "renounceOwnership"
      | "setAuthorizedOracle"
      | "submissions"
      | "submitData"
      | "submitters"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConsensusReached"
      | "DataSubmitted"
      | "OracleAuthorized"
      | "OwnershipTransferred"
      | "PayoutTriggered"
      | "PolicyRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "escrowVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMedian",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policyRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerPolicy",
    values: [BigNumberish, AddressLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedOracle",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submissions",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitData",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitters",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "escrowVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMedian", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "policyRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitData", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ConsensusReachedEvent {
  export type InputTuple = [
    h3Index: BytesLike,
    timestamp: BigNumberish,
    medianRainfall: BigNumberish,
    medianNdvi: BigNumberish
  ];
  export type OutputTuple = [
    h3Index: string,
    timestamp: bigint,
    medianRainfall: bigint,
    medianNdvi: bigint
  ];
  export interface OutputObject {
    h3Index: string;
    timestamp: bigint;
    medianRainfall: bigint;
    medianNdvi: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DataSubmittedEvent {
  export type InputTuple = [
    oracle: AddressLike,
    h3Index: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    oracle: string,
    h3Index: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    oracle: string;
    h3Index: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleAuthorizedEvent {
  export type InputTuple = [oracle: AddressLike, authorized: boolean];
  export type OutputTuple = [oracle: string, authorized: boolean];
  export interface OutputObject {
    oracle: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutTriggeredEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    farmer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [policyId: bigint, farmer: string, amount: bigint];
  export interface OutputObject {
    policyId: bigint;
    farmer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyRegisteredEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    farmer: AddressLike,
    h3Index: BytesLike
  ];
  export type OutputTuple = [policyId: bigint, farmer: string, h3Index: string];
  export interface OutputObject {
    policyId: bigint;
    farmer: string;
    h3Index: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KilimaShieldOracle extends BaseContract {
  connect(runner?: ContractRunner | null): KilimaShieldOracle;
  waitForDeployment(): Promise<this>;

  interface: KilimaShieldOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  escrowVault: TypedContractMethod<[], [string], "view">;

  getMedian: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish, c: BigNumberish],
    [bigint],
    "view"
  >;

  isAuthorizedOracle: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  oracleCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  policyRegistry: TypedContractMethod<[], [string], "view">;

  registerPolicy: TypedContractMethod<
    [
      policyId: BigNumberish,
      farmer: AddressLike,
      h3Index: BytesLike,
      threshold: BigNumberish,
      payoutAmount: BigNumberish
    ],
    [void],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuthorizedOracle: TypedContractMethod<
    [oracle: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  submissions: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish, arg2: AddressLike],
    [
      [bigint, bigint, boolean] & {
        rainfall: bigint;
        ndvi: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  submitData: TypedContractMethod<
    [
      h3Index: BytesLike,
      timestamp: BigNumberish,
      rainfall: BigNumberish,
      ndvi: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  submitters: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish, arg2: BigNumberish],
    [string],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "escrowVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMedian"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish, c: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAuthorizedOracle"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "oracleCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policyRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerPolicy"
  ): TypedContractMethod<
    [
      policyId: BigNumberish,
      farmer: AddressLike,
      h3Index: BytesLike,
      threshold: BigNumberish,
      payoutAmount: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedOracle"
  ): TypedContractMethod<
    [oracle: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submissions"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish, arg2: AddressLike],
    [
      [bigint, bigint, boolean] & {
        rainfall: bigint;
        ndvi: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitData"
  ): TypedContractMethod<
    [
      h3Index: BytesLike,
      timestamp: BigNumberish,
      rainfall: BigNumberish,
      ndvi: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitters"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish, arg2: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ConsensusReached"
  ): TypedContractEvent<
    ConsensusReachedEvent.InputTuple,
    ConsensusReachedEvent.OutputTuple,
    ConsensusReachedEvent.OutputObject
  >;
  getEvent(
    key: "DataSubmitted"
  ): TypedContractEvent<
    DataSubmittedEvent.InputTuple,
    DataSubmittedEvent.OutputTuple,
    DataSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OracleAuthorized"
  ): TypedContractEvent<
    OracleAuthorizedEvent.InputTuple,
    OracleAuthorizedEvent.OutputTuple,
    OracleAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayoutTriggered"
  ): TypedContractEvent<
    PayoutTriggeredEvent.InputTuple,
    PayoutTriggeredEvent.OutputTuple,
    PayoutTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "PolicyRegistered"
  ): TypedContractEvent<
    PolicyRegisteredEvent.InputTuple,
    PolicyRegisteredEvent.OutputTuple,
    PolicyRegisteredEvent.OutputObject
  >;

  filters: {
    "ConsensusReached(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      ConsensusReachedEvent.InputTuple,
      ConsensusReachedEvent.OutputTuple,
      ConsensusReachedEvent.OutputObject
    >;
    ConsensusReached: TypedContractEvent<
      ConsensusReachedEvent.InputTuple,
      ConsensusReachedEvent.OutputTuple,
      ConsensusReachedEvent.OutputObject
    >;

    "DataSubmitted(address,bytes32,uint256)": TypedContractEvent<
      DataSubmittedEvent.InputTuple,
      DataSubmittedEvent.OutputTuple,
      DataSubmittedEvent.OutputObject
    >;
    DataSubmitted: TypedContractEvent<
      DataSubmittedEvent.InputTuple,
      DataSubmittedEvent.OutputTuple,
      DataSubmittedEvent.OutputObject
    >;

    "OracleAuthorized(address,bool)": TypedContractEvent<
      OracleAuthorizedEvent.InputTuple,
      OracleAuthorizedEvent.OutputTuple,
      OracleAuthorizedEvent.OutputObject
    >;
    OracleAuthorized: TypedContractEvent<
      OracleAuthorizedEvent.InputTuple,
      OracleAuthorizedEvent.OutputTuple,
      OracleAuthorizedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayoutTriggered(uint256,address,uint256)": TypedContractEvent<
      PayoutTriggeredEvent.InputTuple,
      PayoutTriggeredEvent.OutputTuple,
      PayoutTriggeredEvent.OutputObject
    >;
    PayoutTriggered: TypedContractEvent<
      PayoutTriggeredEvent.InputTuple,
      PayoutTriggeredEvent.OutputTuple,
      PayoutTriggeredEvent.OutputObject
    >;

    "PolicyRegistered(uint256,address,bytes32)": TypedContractEvent<
      PolicyRegisteredEvent.InputTuple,
      PolicyRegisteredEvent.OutputTuple,
      PolicyRegisteredEvent.OutputObject
    >;
    PolicyRegistered: TypedContractEvent<
      PolicyRegisteredEvent.InputTuple,
      PolicyRegisteredEvent.OutputTuple,
      PolicyRegisteredEvent.OutputObject
    >;
  };
}
