/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MitigationVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateDiscount"
      | "getPolicyMitigations"
      | "mitigationDiscounts"
      | "owner"
      | "renounceOwnership"
      | "setMitigationDiscount"
      | "transferOwnership"
      | "verifyMitigation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DiscountUpdated"
      | "MitigationVerified"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateDiscount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicyMitigations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mitigationDiscounts",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMitigationDiscount",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMitigation",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateDiscount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPolicyMitigations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mitigationDiscounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMitigationDiscount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyMitigation",
    data: BytesLike
  ): Result;
}

export namespace DiscountUpdatedEvent {
  export type InputTuple = [
    mitigationType: string,
    discountPercent: BigNumberish
  ];
  export type OutputTuple = [mitigationType: string, discountPercent: bigint];
  export interface OutputObject {
    mitigationType: string;
    discountPercent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MitigationVerifiedEvent {
  export type InputTuple = [policyId: BigNumberish, mitigationType: string];
  export type OutputTuple = [policyId: bigint, mitigationType: string];
  export interface OutputObject {
    policyId: bigint;
    mitigationType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MitigationVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): MitigationVerifier;
  waitForDeployment(): Promise<this>;

  interface: MitigationVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateDiscount: TypedContractMethod<
    [policyId: BigNumberish],
    [bigint],
    "view"
  >;

  getPolicyMitigations: TypedContractMethod<
    [policyId: BigNumberish],
    [string[]],
    "view"
  >;

  mitigationDiscounts: TypedContractMethod<[arg0: string], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMitigationDiscount: TypedContractMethod<
    [mitigationType: string, discountPercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyMitigation: TypedContractMethod<
    [policyId: BigNumberish, mitigationType: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateDiscount"
  ): TypedContractMethod<[policyId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPolicyMitigations"
  ): TypedContractMethod<[policyId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "mitigationDiscounts"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMitigationDiscount"
  ): TypedContractMethod<
    [mitigationType: string, discountPercent: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyMitigation"
  ): TypedContractMethod<
    [policyId: BigNumberish, mitigationType: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DiscountUpdated"
  ): TypedContractEvent<
    DiscountUpdatedEvent.InputTuple,
    DiscountUpdatedEvent.OutputTuple,
    DiscountUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MitigationVerified"
  ): TypedContractEvent<
    MitigationVerifiedEvent.InputTuple,
    MitigationVerifiedEvent.OutputTuple,
    MitigationVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DiscountUpdated(string,uint256)": TypedContractEvent<
      DiscountUpdatedEvent.InputTuple,
      DiscountUpdatedEvent.OutputTuple,
      DiscountUpdatedEvent.OutputObject
    >;
    DiscountUpdated: TypedContractEvent<
      DiscountUpdatedEvent.InputTuple,
      DiscountUpdatedEvent.OutputTuple,
      DiscountUpdatedEvent.OutputObject
    >;

    "MitigationVerified(uint256,string)": TypedContractEvent<
      MitigationVerifiedEvent.InputTuple,
      MitigationVerifiedEvent.OutputTuple,
      MitigationVerifiedEvent.OutputObject
    >;
    MitigationVerified: TypedContractEvent<
      MitigationVerifiedEvent.InputTuple,
      MitigationVerifiedEvent.OutputTuple,
      MitigationVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
