/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PolicyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedCallers"
      | "deactivatePolicy"
      | "getPoliciesByH3"
      | "getPolicy"
      | "markPaidOut"
      | "owner"
      | "policies"
      | "registerPolicy"
      | "renounceOwnership"
      | "setAuthorizedCaller"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CallerAuthorized"
      | "OwnershipTransferred"
      | "PolicyDeactivated"
      | "PolicyPaidOut"
      | "PolicyRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedCallers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivatePolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoliciesByH3",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markPaidOut",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPolicy",
    values: [BigNumberish, AddressLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedCaller",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivatePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoliciesByH3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markPaidOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CallerAuthorizedEvent {
  export type InputTuple = [caller: AddressLike, authorized: boolean];
  export type OutputTuple = [caller: string, authorized: boolean];
  export interface OutputObject {
    caller: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyDeactivatedEvent {
  export type InputTuple = [policyId: BigNumberish];
  export type OutputTuple = [policyId: bigint];
  export interface OutputObject {
    policyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyPaidOutEvent {
  export type InputTuple = [policyId: BigNumberish];
  export type OutputTuple = [policyId: bigint];
  export interface OutputObject {
    policyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyRegisteredEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    farmer: AddressLike,
    h3Index: BytesLike
  ];
  export type OutputTuple = [policyId: bigint, farmer: string, h3Index: string];
  export interface OutputObject {
    policyId: bigint;
    farmer: string;
    h3Index: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PolicyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PolicyRegistry;
  waitForDeployment(): Promise<this>;

  interface: PolicyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedCallers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  deactivatePolicy: TypedContractMethod<
    [policyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPoliciesByH3: TypedContractMethod<
    [h3Index: BytesLike],
    [bigint[]],
    "view"
  >;

  getPolicy: TypedContractMethod<
    [policyId: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, boolean] & {
        id: bigint;
        farmer: string;
        h3Index: string;
        threshold: bigint;
        payoutAmount: bigint;
        isActive: boolean;
        paidOut: boolean;
      }
    ],
    "view"
  >;

  markPaidOut: TypedContractMethod<
    [policyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  policies: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean, boolean, string, bigint, bigint] & {
        id: bigint;
        farmer: string;
        isActive: boolean;
        paidOut: boolean;
        h3Index: string;
        threshold: bigint;
        payoutAmount: bigint;
      }
    ],
    "view"
  >;

  registerPolicy: TypedContractMethod<
    [
      policyId: BigNumberish,
      farmer: AddressLike,
      h3Index: BytesLike,
      threshold: BigNumberish,
      payoutAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuthorizedCaller: TypedContractMethod<
    [caller: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedCallers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deactivatePolicy"
  ): TypedContractMethod<[policyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPoliciesByH3"
  ): TypedContractMethod<[h3Index: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPolicy"
  ): TypedContractMethod<
    [policyId: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, boolean] & {
        id: bigint;
        farmer: string;
        h3Index: string;
        threshold: bigint;
        payoutAmount: bigint;
        isActive: boolean;
        paidOut: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markPaidOut"
  ): TypedContractMethod<[policyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policies"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean, boolean, string, bigint, bigint] & {
        id: bigint;
        farmer: string;
        isActive: boolean;
        paidOut: boolean;
        h3Index: string;
        threshold: bigint;
        payoutAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerPolicy"
  ): TypedContractMethod<
    [
      policyId: BigNumberish,
      farmer: AddressLike,
      h3Index: BytesLike,
      threshold: BigNumberish,
      payoutAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedCaller"
  ): TypedContractMethod<
    [caller: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CallerAuthorized"
  ): TypedContractEvent<
    CallerAuthorizedEvent.InputTuple,
    CallerAuthorizedEvent.OutputTuple,
    CallerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PolicyDeactivated"
  ): TypedContractEvent<
    PolicyDeactivatedEvent.InputTuple,
    PolicyDeactivatedEvent.OutputTuple,
    PolicyDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyPaidOut"
  ): TypedContractEvent<
    PolicyPaidOutEvent.InputTuple,
    PolicyPaidOutEvent.OutputTuple,
    PolicyPaidOutEvent.OutputObject
  >;
  getEvent(
    key: "PolicyRegistered"
  ): TypedContractEvent<
    PolicyRegisteredEvent.InputTuple,
    PolicyRegisteredEvent.OutputTuple,
    PolicyRegisteredEvent.OutputObject
  >;

  filters: {
    "CallerAuthorized(address,bool)": TypedContractEvent<
      CallerAuthorizedEvent.InputTuple,
      CallerAuthorizedEvent.OutputTuple,
      CallerAuthorizedEvent.OutputObject
    >;
    CallerAuthorized: TypedContractEvent<
      CallerAuthorizedEvent.InputTuple,
      CallerAuthorizedEvent.OutputTuple,
      CallerAuthorizedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PolicyDeactivated(uint256)": TypedContractEvent<
      PolicyDeactivatedEvent.InputTuple,
      PolicyDeactivatedEvent.OutputTuple,
      PolicyDeactivatedEvent.OutputObject
    >;
    PolicyDeactivated: TypedContractEvent<
      PolicyDeactivatedEvent.InputTuple,
      PolicyDeactivatedEvent.OutputTuple,
      PolicyDeactivatedEvent.OutputObject
    >;

    "PolicyPaidOut(uint256)": TypedContractEvent<
      PolicyPaidOutEvent.InputTuple,
      PolicyPaidOutEvent.OutputTuple,
      PolicyPaidOutEvent.OutputObject
    >;
    PolicyPaidOut: TypedContractEvent<
      PolicyPaidOutEvent.InputTuple,
      PolicyPaidOutEvent.OutputTuple,
      PolicyPaidOutEvent.OutputObject
    >;

    "PolicyRegistered(uint256,address,bytes32)": TypedContractEvent<
      PolicyRegisteredEvent.InputTuple,
      PolicyRegisteredEvent.OutputTuple,
      PolicyRegisteredEvent.OutputObject
    >;
    PolicyRegistered: TypedContractEvent<
      PolicyRegisteredEvent.InputTuple,
      PolicyRegisteredEvent.OutputTuple,
      PolicyRegisteredEvent.OutputObject
    >;
  };
}
