# Generated by Django 4.2.30 on 2026-07-01 11:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OracleConsensus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("h3_index", models.CharField(db_index=True, max_length=32)),
                ("metric_name", models.CharField(max_length=64)),
                (
                    "consensus_value",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                ("round_number", models.PositiveIntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OracleSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("oracle_name", models.CharField(max_length=64)),
                ("h3_index", models.CharField(db_index=True, max_length=32)),
                ("metric_name", models.CharField(max_length=64)),
                ("metric_value", models.DecimalField(decimal_places=4, max_digits=12)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("data_hash", models.CharField(max_length=128)),
                ("signature", models.CharField(blank=True, max_length=256)),
                ("consensus_round", models.PositiveIntegerField(default=1)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
