/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPolicyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivatePolicy"
      | "getPoliciesByH3"
      | "getPolicy"
      | "markPaidOut"
      | "registerPolicy"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deactivatePolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoliciesByH3",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markPaidOut",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPolicy",
    values: [BigNumberish, AddressLike, BytesLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "deactivatePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoliciesByH3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markPaidOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPolicy",
    data: BytesLike
  ): Result;
}

export interface IPolicy extends BaseContract {
  connect(runner?: ContractRunner | null): IPolicy;
  waitForDeployment(): Promise<this>;

  interface: IPolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivatePolicy: TypedContractMethod<
    [policyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPoliciesByH3: TypedContractMethod<
    [h3Index: BytesLike],
    [bigint[]],
    "view"
  >;

  getPolicy: TypedContractMethod<
    [policyId: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, boolean] & {
        id: bigint;
        farmer: string;
        h3Index: string;
        threshold: bigint;
        payoutAmount: bigint;
        isActive: boolean;
        paidOut: boolean;
      }
    ],
    "view"
  >;

  markPaidOut: TypedContractMethod<
    [policyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerPolicy: TypedContractMethod<
    [
      policyId: BigNumberish,
      farmer: AddressLike,
      h3Index: BytesLike,
      threshold: BigNumberish,
      payoutAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivatePolicy"
  ): TypedContractMethod<[policyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPoliciesByH3"
  ): TypedContractMethod<[h3Index: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPolicy"
  ): TypedContractMethod<
    [policyId: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, boolean] & {
        id: bigint;
        farmer: string;
        h3Index: string;
        threshold: bigint;
        payoutAmount: bigint;
        isActive: boolean;
        paidOut: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markPaidOut"
  ): TypedContractMethod<[policyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerPolicy"
  ): TypedContractMethod<
    [
      policyId: BigNumberish,
      farmer: AddressLike,
      h3Index: BytesLike,
      threshold: BigNumberish,
      payoutAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
