/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IVerificationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateDiscount"
      | "getPolicyMitigations"
      | "setMitigationDiscount"
      | "verifyMitigation"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculateDiscount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicyMitigations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMitigationDiscount",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMitigation",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateDiscount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPolicyMitigations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMitigationDiscount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyMitigation",
    data: BytesLike
  ): Result;
}

export interface IVerification extends BaseContract {
  connect(runner?: ContractRunner | null): IVerification;
  waitForDeployment(): Promise<this>;

  interface: IVerificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateDiscount: TypedContractMethod<
    [policyId: BigNumberish],
    [bigint],
    "view"
  >;

  getPolicyMitigations: TypedContractMethod<
    [policyId: BigNumberish],
    [string[]],
    "view"
  >;

  setMitigationDiscount: TypedContractMethod<
    [mitigationType: string, discountPercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyMitigation: TypedContractMethod<
    [policyId: BigNumberish, mitigationType: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateDiscount"
  ): TypedContractMethod<[policyId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPolicyMitigations"
  ): TypedContractMethod<[policyId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "setMitigationDiscount"
  ): TypedContractMethod<
    [mitigationType: string, discountPercent: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyMitigation"
  ): TypedContractMethod<
    [policyId: BigNumberish, mitigationType: string],
    [void],
    "nonpayable"
  >;

  filters: {};
}
